= THETA Media Unofficial Guide
:icons: font
:toc: right
:toclevels: 1
:toc-title: Contents
:sectnums:
:source-highlighter: coderay

++++
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-73311422-1', 'auto');
ga('send', 'pageview');
ga('set', 'contentGroup1', 'All RICOH');
</script>
++++

This document is being created to replace the
http://theta360.guide/community-document/community.html[Unofficial Media Guide].
At the time of writing, the THETA S is the newest model. If you're looking for
information in the previous media guide. It's still
http://theta360.guide/community-document/community.html[here]

Post comments and corrections to <http://lists.theta360.guide> in a public
category or direct message
http://lists.theta360.guide/users/jcasman/[@jcasman] or
http://lists.theta360.guide/users/codetricity[@craig] on the lists system.
You must be logged in to send a message.

This is an unofficial, community-generated guide for developing applications
that use 360 media from RICOH THETA cameras.
This is not authorized by RICOH and is based on publicly available information.

Get the latest news and updates on Twitter
**https://twitter.com/theta360dev[@theta360dev]**

==  Resources
=== Official Information

* https://developers.theta360.com/en/docs/v2.1/api_reference/[RICOH THETA API v2.1 reference],
compliant with
https://developers.google.com/streetview/open-spherical-camera/[Open Spherical Camera API level 2] from Google.
* https://developers.theta360.com/en/forums/[THETA Developers Official Forum]
* https://developers.theta360.com/en/docs/sdk/[Official SDK]
* https://theta360.com/en/support/download/[Windows, Mac, iOS, Android apps]

=== Unofficial Information

* http://theta360.guide/community-document/live-streaming.html[Live Streaming Guide]
* http://lists.theta360.guide/[Community Discussion]
* http://theta360.guide/community-document/community.html[Old Media Guide]

// begin overview section

include::overview.adoc[]

include::resize.adoc[]

include::color.adoc[]

include::orientation.adoc[]

include::crop.adoc[]

// begin metadata section

include::metadata.adoc[]

// include::specification.adoc[]

include::sampleApp.adoc[]

// include::platform.adoc[]
